name: Milestone Assessement
on:
  push:
    tags:
      - v1.**
  workflow_dispatch:

jobs:
  maven_build:
    name: Automatic Milestone Evaluation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your code
        uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8.0.392+8
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build pandora.jar with Maven
        run: mvn -B package --file pom.xml

      - name: Download Test suite
        run: |
          wget ${{ secrets.TEST_SUITE_URL }}/autograder.zip -O autograder.zip
          unzip -P ${{ secrets.AUTOGRADER_PASSWORD }} autograder.zip -d autograder

      - name: Set up nodejs to run the tests
        uses: actions/setup-node@v4

      - name: Create Output directory
        run: mkdir results

      - name: run tests
        id: runTests
        run: node autograder/execute.mjs 1 2 3 -f a1 a2 a3 target/pandora.jar

      - name: update report
        if: failure()
        run: echo error

      - name: Create Report Artifact to be downloaded  
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: score-report
          overwrite: true
          path: results/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
           add-paths: results
           commit-message: Automatic Evaluation
           branch: Evaluation/Daily
           branch-suffix: timestamp
           delete-branch: true
           title: Evaluation ${{steps.runTests.outputs.Points}}
           body: ${{steps.runTests.outputs.annotation}}
